version: '3.5'
services: 
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./logs/nginx:/var/log/nginx"

  nginx1:
    image: nginx
    ports: 
      - "8080:80"
    volumes:
      - "./logs/nginx1:/var/log/nginx"
    

